rapid7/insightconnect-workflows

README.md
=> README: Use .icon extension

.github/PULL_REQUEST_TEMPLATE.md, README.md
* Update `.kom` to `.icon` extension in checklist
* Link PR template in README for visibility
=> Update PR checklist with .icon extension

workflows/Office_365_Analysis_with_Virus_Total/Office 365 Analysis Virus Total.icon
This PR is to change the storage plugin version from 1.0.0-release to 1.0.0 in the VT O365 workflow.
=> [DF-2935] - O365 VT Flow - needed to manually change a plugin version

workflows/Automated_Indicator_Enrichment/workflow.spec.yaml, workflows/Office_365_Analysis/workflow.spec.yaml, workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/workflow.spec.yaml, workflows/Office_365_Analysis_with_Virus_Total/workflow.spec.yaml, workflows/Splunk_App_SSH_Alert_IP_Enrichment/workflow.spec.yaml
* Add `attributes` object to spec for defining url resources related to integration for the Hub
```
$ for i in workflows/*/*.yaml; do js-yaml -c $i 1>/dev/null || printf "Failed\n"; done
<empty>
```
=> Hub: Add attributes section to spec

workflows/Office_365_Analysis/Office 365 Analysis.icon, workflows/Office_365_Analysis_with_Virus_Total/Office 365 Analysis Virus Total.icon
This PR fixes the remediation steps on the O365 reference flow and O365 VT flow. They were pointed at the wrong email for remediation.
=> [DF-3399] - fixed remediation

workflows/Automated_Indicator_Enrichment/workflow.spec.yaml, workflows/Office_365_Analysis/workflow.spec.yaml, workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/workflow.spec.yaml, workflows/Office_365_Analysis_with_Virus_Total/workflow.spec.yaml, workflows/Splunk_App_SSH_Alert_IP_Enrichment/workflow.spec.yaml
Rename `attributes` object to `resources`
```
$ for i in */*.yaml; do js-yaml -c $i 1>/dev/null || printf "\n$i failed YAML validation\n"; done
<empty>
```
=> Hub: Rename attributes to resources

workflows/Automated_Indicator_Enrichment/workflow.spec.yaml, workflows/Look_Up_Domains_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_Hashes_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_IPs_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_URLs_with_Recorded_Future/workflow.spec.yaml, workflows/Malicious_Hash_Remediation_with_Cb_Response/workflow.spec.yaml, workflows/Office_365_Analysis/workflow.spec.yaml, workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/workflow.spec.yaml, workflows/Office_365_Analysis_with_Virus_Total/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Mimecast/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Office_365/workflow.spec.yaml, workflows/Splunk_App_SSH_Alert_IP_Enrichment/workflow.spec.yaml
* Add `product` key to spec
* Add `extension` key to spec
```
$ for i in */*.yaml; do js-yaml -c $i 1>/dev/null || printf "\n$i failed YAML validation\n"; done
<empty>
```
=> DF-3514: Hub: Add product and extension keys

workflows/Automated_Indicator_Enrichment/workflow.spec.yaml, workflows/Look_Up_Domains_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_Hashes_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_IPs_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_URLs_with_Recorded_Future/workflow.spec.yaml, workflows/Malicious_Hash_Remediation_with_Cb_Response/workflow.spec.yaml, workflows/Office_365_Analysis/workflow.spec.yaml, workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/workflow.spec.yaml, workflows/Office_365_Analysis_with_Virus_Total/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Mimecast/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Office_365/workflow.spec.yaml, workflows/Splunk_App_SSH_Alert_IP_Enrichment/workflow.spec.yaml
This PR adds the hub_tags to the specs for the workflows in this repo. This PR will be merged during the hackathon
=> Added hub_tags to workflow specs

workflows/InsightIDR_Isolate_Sensor_in_Cb_Response/InsightIDR_Isolate_Sensor_in_Cb_Response.icon, workflows/InsightIDR_Isolate_Sensor_in_Cb_Response/help.md, workflows/InsightIDR_Isolate_Sensor_in_Cb_Response/workflow.spec.yaml
=> InsightIDR Isolate Sensor in Cb Response

workflows/InsightIDR_Enrich_Alert_Data_with_Open_Source_Plugins/InsightIDR_Enrich_Alert_Data_with_Open_Source_Plugins.icon, workflows/InsightIDR_Enrich_Alert_Data_with_Open_Source_Plugins/help.md, workflows/InsightIDR_Enrich_Alert_Data_with_Open_Source_Plugins/workflow.spec.yaml
=> InsightIDR Enrich Alert with Open Source plugins

workflows/InsightIDR_Enable_User_in_Active_Directory/InsightIDR_Enable_User_in_Active_Directory.icon, workflows/InsightIDR_Enable_User_in_Active_Directory/help.md, workflows/InsightIDR_Enable_User_in_Active_Directory/workflow.spec.yaml
=> InsightIDR Enable User in Active Directory

workflows/InsightIDR_Disable_User_in_Active_Directory/InsightIDR-Disable_User_in_Active_Directory.icon, workflows/InsightIDR_Disable_User_in_Active_Directory/help.md, workflows/InsightIDR_Disable_User_in_Active_Directory/workflow.spec.yaml
=> InsightIDR Disable User in Active Directory

workflows/InsightIDR_Create_Issue_in_Jira/InsightIDR_Create_Issue_in_Jira.icon, workflows/InsightIDR_Create_Issue_in_Jira/help.md, workflows/InsightIDR_Create_Issue_in_Jira/idr-Create_Issue_in_Jira.icon, workflows/InsightIDR_Create_Issue_in_Jira/workflow.spec.yaml
=> InsightIDR Create Issue in Jira template

workflows/InsightIDR_Create_Incident_Report_in_ServiceNow/InsightIDR_Create_Incident_Report_in_ServiceNow.icon, workflows/InsightIDR_Create_Incident_Report_in_ServiceNow/help.md, workflows/InsightIDR_Create_Incident_Report_in_ServiceNow/workflow.spec.yaml
=> InsightIDR ServiceNow Template

workflows/InsightIDR_Unsuspend_User_in_Okta/InsightIDR_Unsuspend_User_in_Okta.icon, workflows/InsightIDR_Unsuspend_User_in_Okta/help.md, workflows/InsightIDR_Unsuspend_User_in_Okta/workflow.spec.yaml
=> InsightIDR Unsuspend User in Okta

workflows/InsightIDR_Unisolate_Sensor_in_Cb_Response/InsightIDR_Unisolate_Sensor_in_Cb_Response.icon, workflows/InsightIDR_Unisolate_Sensor_in_Cb_Response/help.md, workflows/InsightIDR_Unisolate_Sensor_in_Cb_Response/workflow.spec.yaml
=> InsightIDR Unisolate sensor in Cb Response

workflows/InsightIDR_Suspend_User_in_Okta/InsightIDR_Suspend_User_in_Okta.icon, workflows/InsightIDR_Suspend_User_in_Okta/help.md, workflows/InsightIDR_Suspend_User_in_Okta/workflow.spec.yaml
=> InsightIDR Suspend User in Okta

workflows/InsightIDR_Isolate_Sensor_in_Cb_Response/workflow.spec.yaml
Describe the proposed changes:
- Remove invalid use_case name
=> Fix reported invalid use case

workflows/Microsoft_Teams_URL_Analysis/Microsoft_Teams_URL_Analysis.icon, workflows/Microsoft_Teams_URL_Analysis/help.md, workflows/Microsoft_Teams_URL_Analysis/workflow.spec.yaml
This PR updates the short description in the .yaml and help.md files. 
No testing was done text-only change.
=> MS Teams - Updated Descriptions

workflows/Automated_Indicator_Enrichment/workflow.spec.yaml, workflows/Create_BMC_Incident_for_Top_Remediations_from_InsightVM/workflow.spec.yaml, workflows/InsightIDR_Create_Incident_Report_in_ServiceNow/workflow.spec.yaml, workflows/InsightIDR_Create_Issue_in_Jira/workflow.spec.yaml, workflows/InsightIDR_Disable_User_in_Active_Directory/workflow.spec.yaml, workflows/InsightIDR_Enable_User_in_Active_Directory/workflow.spec.yaml, workflows/InsightIDR_Enrich_Alert_Data_with_Open_Source_Plugins/workflow.spec.yaml, workflows/InsightIDR_Isolate_Sensor_in_Cb_Response/workflow.spec.yaml, workflows/InsightIDR_Suspend_User_in_Okta/workflow.spec.yaml, workflows/InsightIDR_Unisolate_Sensor_in_Cb_Response/workflow.spec.yaml, workflows/InsightIDR_Unsuspend_User_in_Okta/workflow.spec.yaml, workflows/Look_Up_Domains_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_Hashes_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_IPs_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_URLs_with_Recorded_Future/workflow.spec.yaml, workflows/Malicious_Hash_Remediation_with_Cb_Response/workflow.spec.yaml, workflows/Microsoft_Teams_URL_Analysis/workflow.spec.yaml, workflows/Office_365_Analysis/workflow.spec.yaml, workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/workflow.spec.yaml, workflows/Office_365_Analysis_with_Virus_Total/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Mimecast/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Office_365/workflow.spec.yaml, workflows/Splunk_App_SSH_Alert_IP_Enrichment/workflow.spec.yaml
Update use cases to conform to the new consolidated list. We reduced the original list from ~30 use cases to 14.
YAML validation for spec.
```
$ for i in */workflow.spec.yaml; do js-yaml $i 1>/dev/null || printf "$i\n"; done && printf "Good"
Good
```
=> Hub Tags: Update Use Cases with new consolidated categories

workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon, workflows/Lookup_Vuln_From_Slack/help.md, workflows/Lookup_Vuln_From_Slack/workflow.spec.yaml
workflow import was failing due to plugin version not being updated -- updated plugin version in spec
=> updated vuln DB version

workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/help.md, workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/workflow.spec.yaml
Fixes
```
$ icon-validate .
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
Validator WorkflowTitleValidator failed!
Title is too long, 6 words or less: contains 8
[*] Executing validator WorkflowDescriptionValidator
[*] Executing …
```
=> Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response: Fix missing description in spec, update markdown table

workflows/Block_Sender_in_Office_365_with_Slack/Block_Sender_in_Office_365_with_Slack.icon, workflows/Block_Sender_in_Office_365_with_Slack/help.md, workflows/Block_Sender_in_Office_365_with_Slack/workflow.spec.yaml, workflows/Delete_O365_Emails_with_Slack/Delete_O365_Emails_With_Slack.icon, workflows/Delete_O365_Emails_with_Slack/help.md, workflows/Delete_O365_Emails_with_Slack/workflow.spec.yaml
This PR adds an exclamation point to the slack command used to trigger the O365 exclamation point flows
Made the change in the workflow, imported them to ICON, verified they were triggered when the exclamation point was added.
=> Add leading exclamation point to Slack Flows

workflows/Delete_O365_Emails_with_Slack/help.md, workflows/Delete_O365_Emails_with_Slack/workflow.spec.yaml, workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md, workflows/InsightVM_Top_25_Remediations_to_JIRA/workflow.spec.yaml, workflows/Slack_Chatbot_VirusTotal_Hash_Scan/help.md, workflows/Slack_Chatbot_VirusTotal_Hash_Scan/workflow.spec.yaml, workflows/Slack_Chatbot_VirusTotal_URL_Scan/help.md, workflows/Slack_Chatbot_VirusTotal_URL_Scan/workflow.spec.yaml, workflows/Splunk_App_SSH_Alert_IP_Enrichment/help.md, workflows/Splunk_App_SSH_Alert_IP_Enrichment/workflow.spec.yaml
=> Bump versions of file renamed workflows

workflows/Force_Password_Reset_in_Active_Directory_With_Slack/workflow.spec.yaml
=> Fix yaml error

workflows/Open_Source_Indicator_Enrichment_with_Slack/help.md, workflows/Open_Source_Indicator_Enrichment_with_Slack/workflow.spec.yaml
=> OSI Enrichment with Slack update help and spec

workflows/Force_Password_Reset_in_Azure_AD_from_Microsoft_Teams/Force_Password_Reset_in_Azure_AD_from_Microsoft_Teams.icon, workflows/Force_Password_Reset_in_Azure_AD_from_Microsoft_Teams/help.md, workflows/Force_Password_Reset_in_Azure_AD_from_Microsoft_Teams/workflow.spec.yaml
Updated title, description, key features, keyword tags, setup info, and version
=> Cleanup -- Reset password teams azure

workflows/Block_Sender_in_Office_365_with_Teams/Block_Sender_in_Office_365_with_Teams.icon, workflows/Block_Sender_in_Office_365_with_Teams/help.md, workflows/Block_Sender_in_Office_365_with_Teams/workflow.spec.yaml
updated title, tags, description, key features, setup, & version
=> cleanup -- block sender in o365 from teams

workflows/Slack_Chatbot_Hash_Analysis_with_VirusTotal/Slack_Chatbot_Hash_Analysis_with_VirusTotal.icon, workflows/Slack_Chatbot_Hash_Analysis_with_VirusTotal/help.md, workflows/Slack_Chatbot_Hash_Analysis_with_VirusTotal/workflow.spec.yaml
updated title, keyword tags, description, key features, requirements, setup info, & version
=> cleanup - enrich hash with slack

workflows/GeoIP_Lookup_with_Slack/help.md, workflows/GeoIP_Lookup_with_Slack/workflow.spec.yaml
=> GeoIP Lookup from Slack: Code block formatting and description fix

workflows/Suspend_User_in_Azure_AD_from_Slack/Suspend_User_in_Azure_AD_from_Slack.icon, workflows/Suspend_User_in_Azure_AD_from_Slack/help.md, workflows/Suspend_User_in_Azure_AD_from_Slack/workflow.spec.yaml
Updated title, description, tags, key features, setup info, and version
=> cleanup - disable azure user with slack

workflows/Force_Password_Reset_in_Active_Directory_With_Slack/Force_Password_Reset_in_Active_Directory_With_Slack.icon, workflows/Force_Password_Reset_in_Active_Directory_With_Slack/help.md, workflows/Force_Password_Reset_in_Active_Directory_With_Slack/workflow.spec.yaml
updated title, description, key features, tags, setup info, & version history
=> cleanup - reset password AD slack

workflows/Force_Password_Reset_in_Azure_AD_from_Slack/Force_Password_Reset_in_Azure_AD_from_Slack.icon, workflows/Force_Password_Reset_in_Azure_AD_from_Slack/help.md, workflows/Force_Password_Reset_in_Azure_AD_from_Slack/workflow.spec.yaml
Updated title, description, key features, tags, setup info, & version history
=> cleanup - password reset azure slack

workflows/Delete_O365_Emails_With_Slack/Delete_O365_Emails_With_Slack.icon, workflows/Delete_O365_Emails_With_Slack/help.md, workflows/Delete_O365_Emails_With_Slack/workflow.spec.yaml
updated title, description, key features, tags, setup info, & version history
=> cleanup - delete office365 email with slack

workflows/Delete_Emails_from_O365_With_Microsoft_Teams/Delete_Emails_from_O365_With_Microsoft_Teams.icon, workflows/Delete_Emails_from_O365_With_Microsoft_Teams/help.md, workflows/Delete_Emails_from_O365_With_Microsoft_Teams/workflow.spec.yaml
Updated title, description, key features, setup documentation, tags, and version
=> Cleanup - delete email in O365 from Teams

workflows/Purge_Office_365_Emails_with_Microsoft_Teams/Purge_Office_365_Emails_with_Microsoft_Teams.icon, workflows/Purge_Office_365_Emails_with_Microsoft_Teams/help.md, workflows/Purge_Office_365_Emails_with_Microsoft_Teams/workflow.spec.yaml
updated title, tags, description, key features, setup info, & version
=> Cleanup purge email teams

workflows/Block_Sender_in_Office_365_with_Slack/help.md, workflows/Block_Sender_in_Office_365_with_Slack/workflow.spec.yaml
updated description, key features, setup info, usage info, tags, and version history
=> cleanup - block sender o365 slack

workflows/Block_Sender_in_Office_365_with_Slack/help.md, workflows/Force_Password_Reset_in_Azure_AD_from_Slack/help.md, workflows/GeoIP_Lookup_with_Slack/help.md, workflows/InsightVM_Top_10_Vuln_Assets_to_Slack/help.md, workflows/Lookup_Vuln_From_Slack/help.md, workflows/Open_Source_Indicator_Enrichment_with_Slack/help.md, workflows/Slack_Chatbot_Hash_Analysis_with_VirusTotal/help.md, workflows/Slack_Chatbot_URL_Analysis_with_VirusTotal/help.md, workflows/Suspend_AD_LDAP_User_from_Slack/help.md, workflows/Suspend_User_in_Azure_AD_from_Microsoft_Teams/help.md, workflows/Suspend_User_in_Azure_AD_from_Slack/help.md, workflows/Top_Remediations_For_Asset_In_Slack/help.md, workflows/URLScan_with_Slack/help.md, workflows/Unshorten_URL_with_Slack/help.md
Standardize on convention for Slackbot in documentation
=> Use Slackbot convention in examples

workflows/Purge_Office_365_Emails_with_Slack/help.md, workflows/Purge_Office_365_Emails_with_Slack/workflow.spec.yaml
updated description, key features, setup, tags, and version history
=> cleanup - purge office365 emails with slack

workflows/Slack_Chatbot_URL_Analysis_with_VirusTotal/Slack_Chatbot_URL_Analysis_with_VirusTotal.icon, workflows/Slack_Chatbot_URL_Analysis_with_VirusTotal/help.md, workflows/Slack_Chatbot_URL_Analysis_with_VirusTotal/workflow.spec.yaml
Removed "changemes" from slack workflow and updated to use threads
Also updated title, description, key features, setup, usage, tags, requirements, and version history
=> Cleanup enrich url slack

workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams.icon, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/help.md, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/workflow.spec.yaml
=> renamed workflow

workflows/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack.icon, workflows/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack/help.md, workflows/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack/workflow.spec.yaml
=> Rename Exchange workflow

workflows/GeoIP_Lookup_with_Slack/GeoIP_Lookup_with_Slack.icon
Previous PR for this workflow was to rename the ICON file, but the new renamed file was not adde d to the repo.  This is fix the builds for the workflow.
=> Renamed icon file, but failed to add it properly

workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/help.md, workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/workflow.spec.yaml, workflows/InsightIDR_Impossible_Location_with_Slack_Chatbot/help.md, workflows/InsightIDR_Impossible_Location_with_Slack_Chatbot/workflow.spec.yaml, workflows/InsightIDR_MultiCountry_Auth_and_Remediation/help.md, workflows/InsightIDR_MultiCountry_Auth_and_Remediation/workflow.spec.yaml, workflows/Malicious_Hash_Remediation_with_Cb_Response/help.md, workflows/Malicious_Hash_Remediation_with_Cb_Response/workflow.spec.yaml, workflows/Out_Of_Office_AutoResponse_User_Containment/help.md, workflows/Out_Of_Office_AutoResponse_User_Containment/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Mimecast/help.md, workflows/Spearphishing_Remediation_with_Mimecast/workflow.spec.yaml, workflows/Spearphishing_Remediation_with_Office_365/help.md, workflows/Spearphishing_Remediation_with_Office_365/workflow.spec.yaml, workflows/Suspicious_User_Login_with_IDR_and_Slack_Chatops/help.md, workflows/Suspicious_User_Login_with_IDR_and_Slack_Chatops/workflow.spec.yaml
added idr product tags, bumped versions
=> added insightidr product tags

workflows/Enrich_File_Hash_with_Microsoft_Teams/help.md, workflows/Enrich_File_Hash_with_Microsoft_Teams/workflow.spec.yaml
* Updated title in workflow.spec.yaml
* Version bumped
* Updated changelog in help.md
```
```
=> Change name from Slack to Microsoft Teams

workflows/Disable_User_in_Active_Directory_from_Microsoft_Teams/Disable_User_in_Active_Directory_from_Microsoft_Teams.icon, workflows/Disable_User_in_Active_Directory_from_Microsoft_Teams/help.md, workflows/Disable_User_in_Active_Directory_from_Microsoft_Teams/workflow.spec.yaml, workflows/Suspend_User_in_Azure_AD_from_Microsoft_Teams/Suspend_User_in_Azure_AD_from_Microsoft_Teams.icon, workflows/Suspend_User_in_Azure_AD_from_Microsoft_Teams/help.md, workflows/Suspend_User_in_Azure_AD_from_Microsoft_Teams/workflow.spec.yaml
=> Disable teams updates

workflows/Suspend_AD_LDAP_User_from_Slack/Suspend_AD_LDAP_User_from_Slack.icon, workflows/Suspend_AD_LDAP_User_from_Slack/help.md, workflows/Suspend_AD_LDAP_User_from_Slack/workflow.spec.yaml, workflows/Suspend_User_in_Azure_AD_from_Slack/Suspend_User_in_Azure_AD_from_Slack.icon, workflows/Suspend_User_in_Azure_AD_from_Slack/help.md, workflows/Suspend_User_in_Azure_AD_from_Slack/workflow.spec.yaml
=> Slack disable updates

workflows/Get_InsightVM_Host_Info_From_Slack/workflow.spec.yaml, workflows/InsightVM_Top_10_Vuln_Assets_to_Slack/help.md, workflows/InsightVM_Top_10_Vuln_Assets_to_Slack/workflow.spec.yaml, workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md, workflows/InsightVM_Top_25_Remediations_to_JIRA/workflow.spec.yaml, workflows/InsightVM_Top_25_Remediations_to_ServiceNow/help.md, workflows/InsightVM_Top_25_Remediations_to_ServiceNow/workflow.spec.yaml, workflows/InsightVM_Top_25_Remediations_to_Zendesk/help.md, workflows/InsightVM_Top_25_Remediations_to_Zendesk/workflow.spec.yaml, workflows/Lookup_Vuln_From_Slack/help.md, workflows/Lookup_Vuln_From_Slack/workflow.spec.yaml, workflows/Top_Remediations_For_Asset_In_Slack/help.md, workflows/Top_Remediations_For_Asset_In_Slack/workflow.spec.yaml
added tags, small updates to help docs, bumped versions
=> added insightvm product tags

workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams.icon, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/help.md, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/workflow.spec.yaml
Remove hardcoded value from workflow. Set to change_me instead.
=> Post Office 365 Phishing Alerts to Microsoft Teams: Remove hardcoded items

workflows/Purge_Office_365_Emails_with_Microsoft_Teams/Purge_Office_365_Emails_with_Microsoft_Teams.icon, workflows/Purge_Office_365_Emails_with_Microsoft_Teams/help.md, workflows/Purge_Office_365_Emails_with_Microsoft_Teams/workflow.spec.yaml, workflows/Purge_Office_365_Emails_with_Slack/Purge_Office_365_Emails_with_Slack.icon, workflows/Purge_Office_365_Emails_with_Slack/help.md, workflows/Purge_Office_365_Emails_with_Slack/workflow.spec.yaml
Update trigger commands for
* Purge_Office_365_Emails_with_Microsoft_Teams
* Purge_Office_365_Emails_with_Slack
=> Delete Emails: Update purge commands to delete emails

workflows/Microsoft_Office_365_Email_Indicators_to_Slack/Microsoft_Office_365_Email_Indicators_to_Slack.icon, workflows/Microsoft_Office_365_Email_Indicators_to_Slack/help.md, workflows/Microsoft_Office_365_Email_Indicators_to_Slack/workflow.spec.yaml
=> Post Office 365 Phishing Alerts to Slack

workflows/Force_Password_Reset_in_Azure_AD_from_Slack/Force_Password_Reset_in_Azure_AD_from_Slack.icon, workflows/Force_Password_Reset_in_Azure_AD_from_Slack/help.md, workflows/Force_Password_Reset_in_Azure_AD_from_Slack/workflow.spec.yaml, workflows/URLScan_with_Slack/URLScan_with_Slack.icon, workflows/URLScan_with_Slack/help.md, workflows/URLScan_with_Slack/workflow.spec.yaml
Remove hardcoded channel in Slack workflows
=> Slack bot remove hardcoded channel

workflows/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack.icon, workflows/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack/help.md, workflows/Parse_Phishing_Indicators_with_Microsoft_Exchange_from_Slack/workflow.spec.yaml, workflows/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams.icon, workflows/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams/help.md, workflows/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams/workflow.spec.yaml
=> Post Exchange Phishing Alerts to Slack/Microsoft Teams

workflows/Microsoft_Teams_URL_Analysis/help.md, workflows/Microsoft_Teams_URL_Analysis/workflow.spec.yaml
=> Bump MS Teams URL Analysis Version

workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/help.md, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/workflow.spec.yaml
=> Remove extra period

workflows/Force_Password_Reset_in_Active_Directory_With_Slack/Force_Password_Reset_in_Active_Directory_With_Slack.icon, workflows/Force_Password_Reset_in_Active_Directory_With_Slack/help.md, workflows/Force_Password_Reset_in_Active_Directory_With_Slack/workflow.spec.yaml, workflows/Force_Password_Reset_in_Active_Directory_with_Microsoft_Teams/Force_Password_Reset_in_Active_Directory_with_Microsoft_Teams.icon, workflows/Force_Password_Reset_in_Active_Directory_with_Microsoft_Teams/help.md, workflows/Force_Password_Reset_in_Active_Directory_with_Microsoft_Teams/workflow.spec.yaml
```
```
ran successfully icon-validate on both workflows.
=> Force Password Reset in Active Directory from Slack/Microsoft Teams

workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/help.md, workflows/Force_Password_Reset_in_Azure_AD_from_Slack/help.md, workflows/Get_InsightVM_Host_Info_From_Slack/help.md, workflows/InsightIDR_Impossible_Location_with_Slack_Chatbot/help.md, workflows/InsightIDR_MultiCountry_Auth_and_Remediation/help.md, workflows/InsightVM_Top_10_Vuln_Assets_to_Slack/help.md, workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md, workflows/InsightVM_Top_25_Remediations_to_ServiceNow/help.md, workflows/InsightVM_Top_25_Remediations_to_Zendesk/help.md, workflows/Look_Up_Domains_with_Recorded_Future/help.md, workflows/Look_Up_Hashes_with_Recorded_Future/help.md, workflows/Look_Up_IPs_with_Recorded_Future/help.md, workflows/Look_Up_URLs_with_Recorded_Future/help.md, workflows/Lookup_Vuln_From_Slack/help.md, workflows/Malicious_Hash_Remediation_with_Cb_Response/help.md, workflows/Out_Of_Office_AutoResponse_User_Containment/help.md, workflows/Spearphishing_Remediation_with_Mimecast/help.md, workflows/Spearphishing_Remediation_with_Office_365/help.md, workflows/Suspicious_User_Login_with_IDR_and_Slack_Chatops/help.md, workflows/Top_Remediations_For_Asset_In_Slack/help.md
Updated workflow requirements to reflect the need for InsightConnect license. Small adjustments to Setup where needed based on the new import process.
=> Update VM & IDR workflow requirements

workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams.icon, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/help.md, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/workflow.spec.yaml
This PR fixes an issue where a variable was declared incorrectly in the workflow. It had extra {{ in a for each loop
Workflow was imported into ICON and variable was verified to be fixed.
=> [SOAR-1296] - Fix invalid var in Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams

workflows/Deploy_Patch_With_BigFix_From_Teams/workflow.spec.yaml
=> Fix Deploy_Patch_With_BigFix_From_Teams Name Typo

workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md, workflows/Lookup_Vulnerable_Hosts_From_Slack/workflow.spec.yaml
=> Lookup Vulnerable Hosts: Fix validation issues

workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml
This PR updates the following workflows to use the latest plugin version: 
Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack
Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams
Testing: 
Both were imported to ICON to verify functionality.
=> Fortinet update

workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/Block_Host_with_Palo_Alto_Firewall_from_Slack.icon, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/help.md, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/workflow.spec.yaml
Update Palo Alto workflows to latest version of plugins.
Imported each workflow to verify that they are valid.
=> updated palo alto firewall version to 6

workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/help.md
=> fix typos in Check Host Block Status with Fortinet Firewall workflows help.md

workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/workflow.spec.yaml
This PR updates both the Check Block Status with Check Point workflows to use the latest version of the CheckPoint NGFW plugin. 
Both workflows were imported, verified they were using the latest version and tested in their respective chat program. Both worked as expected.
=> [SOAR-1466] - Update CheckPoint Workflows to latest version of Plugin

workflows/Get_InsightVM_Host_Info_From_Slack/Get_InsightVM_Host_Info_From_Slack.icon, workflows/Get_InsightVM_Host_Info_From_Slack/workflow.spec.yaml, workflows/InsightVM_Top_25_Remediations_to_JIRA/InsightVM_Top_25_Remediations_to_JIRA.icon, workflows/InsightVM_Top_25_Remediations_to_JIRA/workflow.spec.yaml, workflows/InsightVM_Top_25_Remediations_to_ServiceNow/InsightVM_Top_25_Remediations_to_ServiceNow.icon, workflows/InsightVM_Top_25_Remediations_to_ServiceNow/workflow.spec.yaml, workflows/InsightVM_Top_25_Remediations_to_Zendesk/InsightVM_Top_25_Remediations_to_Zendesk.icon, workflows/InsightVM_Top_25_Remediations_to_Zendesk/workflow.spec.yaml, workflows/Manage_Vulnerability_Exception_Requests_From_Slack/Manage_Vulnerability_Exception_Requests_From_Slack.icon, workflows/Manage_Vulnerability_Exception_Requests_From_Slack/workflow.spec.yaml, workflows/Top_Remediations_For_Asset_In_Slack/Get_InsightVM_Top_Remediations_From_Slack.icon, workflows/Top_Remediations_For_Asset_In_Slack/workflow.spec.yaml, workflows/Top_Remediations_For_Asset_In_Teams/Top_Remediations_For_Asset_In_Teams.icon, workflows/Top_Remediations_For_Asset_In_Teams/workflow.spec.yaml
Updated workflow titles & spec.yaml names
=> updated workflow names for vulnerability toolkit

workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Sender_in_Office_365_with_Teams/Block_Sender_in_Office_365_with_Teams.icon, workflows/Block_Sender_in_Office_365_with_Teams/help.md, workflows/Block_Sender_in_Office_365_with_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/workflow.spec.yaml
This PR updates the following to the latest version of Microsoft Teams: 
Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams
Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams
Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams
Block_Sender_in_Office_365_with_Teams
Check_Host_Block_Status_with_Check_Point_Firewall_from_Microsoft_Teams
Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams
Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams
Each workflow was validated using ICON-Validate. Each workflow was imported into ICON.
=> Update Workflows to latest version of Microsoft Teams

workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams.icon, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/help.md, workflows/Microsoft_Office_365_Email_Indicators_to_Microsoft_Teams/workflow.spec.yaml, workflows/Microsoft_Teams_URL_Analysis/Microsoft_Teams_URL_Analysis.icon, workflows/Microsoft_Teams_URL_Analysis/help.md, workflows/Microsoft_Teams_URL_Analysis/workflow.spec.yaml, workflows/Open_Source_Indicator_Enrichment_with_Microsoft_Teams/Open_Source_Indicator_Enrichment_with_Microsoft_Teams.icon, workflows/Open_Source_Indicator_Enrichment_with_Microsoft_Teams/help.md, workflows/Open_Source_Indicator_Enrichment_with_Microsoft_Teams/workflow.spec.yaml, workflows/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams.icon, workflows/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams/help.md, workflows/Post_Exchange_Phishing_Alerts_to_Microsoft_Teams/workflow.spec.yaml, workflows/Post_Gmail_Phishing_Alerts_to_Microsoft_Teams/Post_Gmail_Phishing_Alerts_to_Microsoft_Teams.icon, workflows/Post_Gmail_Phishing_Alerts_to_Microsoft_Teams/help.md, workflows/Post_Gmail_Phishing_Alerts_to_Microsoft_Teams/workflow.spec.yaml, workflows/Purge_Office_365_Emails_with_Microsoft_Teams/Purge_Office_365_Emails_with_Microsoft_Teams.icon, workflows/Purge_Office_365_Emails_with_Microsoft_Teams/help.md, workflows/Purge_Office_365_Emails_with_Microsoft_Teams/workflow.spec.yaml, workflows/Revoke_User_Session_in_Azure_AD_with_Microsoft_Teams/Revoke_User_Session_in_Azure_AD_with_Microsoft_Teams.icon, workflows/Revoke_User_Session_in_Azure_AD_with_Microsoft_Teams/help.md, workflows/Revoke_User_Session_in_Azure_AD_with_Microsoft_Teams/workflow.spec.yaml, workflows/Suspend_User_in_Azure_AD_from_Microsoft_Teams/Suspend_User_in_Azure_AD_from_Microsoft_Teams.icon, workflows/Suspend_User_in_Azure_AD_from_Microsoft_Teams/help.md, workflows/Suspend_User_in_Azure_AD_from_Microsoft_Teams/workflow.spec.yaml, workflows/Top_Remediations_For_Asset_In_Teams/Top_Remediations_For_Asset_In_Teams.icon, workflows/Top_Remediations_For_Asset_In_Teams/help.md, workflows/Top_Remediations_For_Asset_In_Teams/workflow.spec.yaml, workflows/Unshorten_URL_with_Microsoft_Teams/Unshorten_URL_with_Microsoft_Teams.icon, workflows/Unshorten_URL_with_Microsoft_Teams/help.md, workflows/Unshorten_URL_with_Microsoft_Teams/workflow.spec.yaml
Update Workflows to new version of teams
=> Teams bug fix

workflows/Lookup_Exploit_with_AttackerKB_from_Microsoft_Teams/Lookup_Exploit_with_AttackerKB_from_Microsoft_Teams.icon, workflows/Lookup_Exploit_with_AttackerKB_from_Microsoft_Teams/help.md, workflows/Lookup_Exploit_with_AttackerKB_from_Microsoft_Teams/workflow.spec.yaml, workflows/Lookup_InsightVM_Host_Info_From_Teams/Lookup_InsightVM_Host_Info_From_Teams.icon, workflows/Lookup_InsightVM_Host_Info_From_Teams/help.md, workflows/Lookup_Vuln_From_Teams/Lookup_Vuln_From_Teams.icon, workflows/Lookup_Vuln_From_Teams/help.md, workflows/Lookup_Vuln_From_Teams/workflow.spec.yaml, workflows/Lookup_Vulnerable_Hosts_From_Teams/Lookup_Vulnerable_Hosts_From_Teams.icon, workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md, workflows/Lookup_Vulnerable_Hosts_From_Teams/workflow.spec.yaml
=> Teams bug fix 2.0

workflows/Top_Remediations_For_Asset_In_Teams/Top_Remediations_For_Asset_In_Teams.icon, workflows/Top_Remediations_For_Asset_In_Teams/help.md, workflows/Top_Remediations_For_Asset_In_Teams/workflow.spec.yaml
Removed a type conversion step that was causing the workflow to error. Type conversion was trying to convert string to string. Bumped workflow version & -1 type conversion step in help.md
=> Updated Workflow: Remove Unnecessary Type Conversion

workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Check_Point_Firewall_from_Slack/help.md, workflows/Block_Host_with_Check_Point_Firewall_from_Slack/workflow.spec.yaml, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml
=> Help amendments

README.md
Fix broken link to contributor's guide
=> Fix broken link to contrib guide

workflows/Lookup_InsightVM_Host_Info_From_Teams/Lookup_InsightVM_Host_Info_From_Teams.icon, workflows/Lookup_InsightVM_Host_Info_From_Teams/help.md, workflows/Lookup_InsightVM_Host_Info_From_Teams/workflow.spec.yaml
=> Lookup_InsightVM_Host_Info_From_Teams: Fix variable reported by Brandon McClure

workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/Blacklist_Hash_with_CylancePROTECT_from_Slack.icon, workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/help.md, workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/workflow.spec.yaml, workflows/Blacklist_Hash_with_SentinelOne_from_Slack/Blacklist_Hash_with_SentinelOne_from_Slack.icon, workflows/Blacklist_Hash_with_SentinelOne_from_Slack/help.md, workflows/Blacklist_Hash_with_SentinelOne_from_Slack/workflow.spec.yaml
Print Job URL in Blacklist workflows when failure occurs to conveniently link user to contextual information.
=> Add Job URL

workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack.icon, workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/help.md, workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/workflow.spec.yaml
* Fix old hash value in decision path
* Set change_me steps in Slack channel inputs
=> Update Trend Micro Blacklist workflow

workflows/Lookup_Vulnerable_Hosts_From_Teams/Lookup_Vulnerable_Hosts_From_Teams.icon, workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
Revised Vuln DB version in both Help & workflow
=> revise vulndb version

workflows/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack.icon, workflows/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack/help.md, workflows/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack/workflow.spec.yaml
=> Update Trend Micro Apex plugin in Slack Quarantine workflow

workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack.icon, workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/help.md, workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/workflow.spec.yaml
=> Update Trend Micro plugin in Slack Blacklist workflow

workflows/Blacklist_Hash_with_SentinelOne_from_Microsoft_Teams/Blacklist_Hash_with_SentinelOne_from_Microsoft_Teams.icon
Follow-up fix to this PR https://github.com/rapid7/insightconnect-workflows/pull/244
=> Add missing workflow file for Blacklist Hash with SentinelOne from Microsoft Teams

workflows/Blacklist_Hash_with_CylancePROTECT_from_Microsoft_Teams/Blacklist_Hash_with_CylancePROTECT_from_Microsoft_Teams.icon, workflows/Blacklist_Hash_with_CylancePROTECT_from_Microsoft_Teams/help.md, workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/Blacklist_Hash_with_CylancePROTECT_from_Slack.icon, workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/help.md
=> Update workflows with proper branding of plugin in Cylance Workflows

workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/Quarantine_Endpoint_with_SentinelOne_from_Slack.icon, workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/help.md, workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/workflow.spec.yaml
=> SentinelOne Quarantine workflow: Fix product name in Slack message

workflows/Black_Hash_with_Symantec_Endpoint_Protection_from_Slack/Black_Hash_with_Symantec_Endpoint_Protection_from_Slack.icon, workflows/Black_Hash_with_Symantec_Endpoint_Protection_from_Slack/help.md, workflows/Black_Hash_with_Symantec_Endpoint_Protection_from_Slack/workflow.spec.yaml, workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/Blacklist_Hash_with_CylancePROTECT_from_Slack.icon, workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/help.md, workflows/Blacklist_Hash_with_CylancePROTECT_from_Slack/workflow.spec.yaml, workflows/Blacklist_Hash_with_SentinelOne_from_Slack/Blacklist_Hash_with_SentinelOne_from_Slack.icon, workflows/Blacklist_Hash_with_SentinelOne_from_Slack/help.md, workflows/Blacklist_Hash_with_SentinelOne_from_Slack/workflow.spec.yaml, workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack.icon, workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/help.md, workflows/Blacklist_Indicators_with_Trend_Micro_Apex_from_Slack/workflow.spec.yaml, workflows/Quarantine_Endpoint_with_Broadcom_Symantec_Endpoint_Protection_from_Slack/Quarantine_Endpoint_with_Broadcom_Symantec_Endpoint_Protection_from_Slack.icon, workflows/Quarantine_Endpoint_with_Broadcom_Symantec_Endpoint_Protection_from_Slack/help.md, workflows/Quarantine_Endpoint_with_Broadcom_Symantec_Endpoint_Protection_from_Slack/workflow.spec.yaml, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack.icon, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack/help.md, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack/workflow.spec.yaml, workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/Quarantine_Endpoint_with_SentinelOne_from_Slack.icon, workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/help.md, workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/workflow.spec.yaml, workflows/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack.icon, workflows/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack/help.md, workflows/Quarantine_Endpoint_with_Trend_Micro_Apex_from_Slack/workflow.spec.yaml
Tested all Blacklist and Quarantine workflows and they were all successful
=> Pass channel to all subsequent Slack steps in EDR workflows for easier configuration

workflows/Block_Host_with_Check_Point_Firewall_from_Slack/Block_Host_with_Check_Point_Firewall_from_Slack.icon, workflows/Block_Host_with_Check_Point_Firewall_from_Slack/help.md, workflows/Block_Host_with_Check_Point_Firewall_from_Slack/workflow.spec.yaml, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/Block_Host_with_Fortinet_Firewall_from_Slack.icon, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/Block_Host_with_Palo_Alto_Firewall_from_Slack.icon, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/help.md, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/workflow.spec.yaml
=> Pass channel to all subsequent Slack steps in Firewall workflows for easier configuration

workflows/Lookup_Vuln_From_Teams/Lookup_Vuln_From_Teams.icon, workflows/Lookup_Vuln_From_Teams/help.md, workflows/Lookup_Vuln_From_Teams/workflow.spec.yaml
=> Consolidated Teams Settings into one step

README.md
Link to dev videos for workflow building and contributing
=> Add video links to README

workflows/Virtually_Patch_Vulnerabilities_found_by_InsightVM_with_Deep_Security/help.md, workflows/Virtually_Patch_Vulnerabilities_found_by_InsightVM_with_Deep_Security/workflow.spec.yaml
Fix issue in workflow name causing failure to import
=> Fix import failure for: Virtually Patch Vulnerabilities found by InsightVM with Deep Security

workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml
Update for Fortinet FortiGate 4.0.3
Add continue on failure to FortiGate action and add new teams/slack message informing the user that the workflow has failed
Both workflows pass validation
Both workflows tested in integrations testing lab
=> [SOAR 1786 ]Check host Fortinet workflow fixes

workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/Block_Host_with_Fortinet_Firewall_from_Slack.icon, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml
Both workflows passing validation
Both Workflows tested with new and existing addresses.
Both workflows forced to fail. successful message to team/slack informing that the workflow failed.
MS Teams
[*] Executing validator …
=> [SOAR 1789] Bug fixes and stability improvements for Block Host with FortiGate workflows

workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response.icon, workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/help.md, workflows/Blacklist_Malicious_Hashes_with_VirusTotal_and_Carbon_Black_Response/workflow.spec.yaml, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Microsoft_Teams/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Microsoft_Teams.icon, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Microsoft_Teams/help.md, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Microsoft_Teams/workflow.spec.yaml, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack.icon, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack/help.md, workflows/Quarantine_Endpoint_with_Carbon_Black_Cloud_from_Slack/workflow.spec.yaml
added "VMware" before Carbon Black everywhere I could
=> Updated carbon black branding

workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Check_Point_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Check_Point_Firewall_from_Slack/Block_Host_with_Check_Point_Firewall_from_Slack.icon, workflows/Block_Host_with_Check_Point_Firewall_from_Slack/help.md, workflows/Block_Host_with_Check_Point_Firewall_from_Slack/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Check_Point_Firewall_from_Slack/workflow.spec.yaml
Update step messages and improve documentation in Block Host workflows to indicate the Checkpoint steps that need to be updated to manage address objects.
=> Minor updates to Checkpoint workflows

workflows/MDR_Active_Response_Disable_User_with_Active_Directory/workflow.spec.yaml, workflows/MDR_Active_Response_Enable_User_with_Active_Directory/workflow.spec.yaml, workflows/MDR_Active_Response_Isolate_Sensor_with_VMware_Carbon_Black_EDR/workflow.spec.yaml, workflows/MDR_Active_Response_Router/workflow.spec.yaml, workflows/MDR_Active_Response_Unisolate_Sensor_with_VMware_Carbon_Black_EDR/workflow.spec.yaml, workflows/MDR_Active_Response_Unquarantine_Asset_with_Insight_Agent/workflow.spec.yaml
=> Change "Obsolete" to "Hidden"

workflows/MDR_Active_Response_Router/MDR_Active_Response_Router.icon, workflows/MDR_Active_Response_Router/help.md, workflows/MDR_Active_Response_Router/workflow.spec.yaml
* Version bump
* Update changelog
```
```
=> Fix null issue breaking the filter step

workflows/Check_Host_Block_Status_with_Cisco_ASA_from_Slack/Check_Host_Block_Status_with_Cisco_ASA_from_Slack.icon, workflows/Check_Host_Block_Status_with_Cisco_ASA_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Cisco_ASA_from_Slack/workflow.spec.yaml, workflows/Quarantine_Endpoint_with_Microsoft_Defender_ATP_from_Slack/Quarantine_Endpoint_with_Microsoft_Defender_ATP_from_Slack.icon, workflows/Quarantine_Endpoint_with_Microsoft_Defender_ATP_from_Slack/help.md, workflows/Quarantine_Endpoint_with_Microsoft_Defender_ATP_from_Slack/workflow.spec.yaml
=> Update default channels

workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/workflow.spec.yaml, workflows/Hello_IDR_Alert/workflow.spec.yaml, workflows/Hello_World/workflow.spec.yaml
Hiding the beginner workflows we will recommend in the Discover Experience
=> mark beginner workflows as obsolete

workflows/Hello_World/Hello_World.icon, workflows/Hello_World/help.md, workflows/Hello_World/workflow.spec.yaml
Added link to Discover tab in artifact, updated description, bumped version
```
```
=> Updated Hello World workflow

workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd.icon, workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/help.md, workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/workflow.spec.yaml
Updated artifact, updated description, version bump, removed hidden tag (this workflow does provide value to IDR users!)
=> Updated Threat Crowd Discover Workflow

workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml
- Update Fortinet FortiGate, Microsoft Teams, and HTML plugins to latest versions
```
[*] Executing validator …
```
=> SOAR_2917_Update_Plugins_in_Check_Block_Status_from_MS_Teams

workflows/Block_Host_with_Fortinet_Firewall_from_Slack/Block_Host_with_Fortinet_Firewall_from_Slack.icon, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml
- Update Fortinet FortiGate plugin to latest version
```
[*] …
```
=> SOAR_2918_Block_Host_from_Fortinet_Firewall_from_Slack

workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Fortinet_Firewall_from_Microsoft_Teams/workflow.spec.yaml
- Bump Fortinet Fortigate, HTML, and Microsoft Teams plugins
``` …
```
=> SOAR_2919 Update Plugin Versions

workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Slack/workflow.spec.yaml
- Update Fortinet FortiGate plugin to latest version
```
[*] …
```
=> Update Fortinet Fortigate plugin

workflows/MDR_Active_Response_Disable_User_with_Active_Directory/MDR_Active_Response_Disable_User_with_Active_Directory.icon, workflows/MDR_Active_Response_Disable_User_with_Active_Directory/help.md, workflows/MDR_Active_Response_Disable_User_with_Active_Directory/workflow.spec.yaml, workflows/MDR_Active_Response_Enable_User_with_Active_Directory/MDR_Active_Response_Enable_User_with_Active_Directory.icon, workflows/MDR_Active_Response_Enable_User_with_Active_Directory/help.md, workflows/MDR_Active_Response_Enable_User_with_Active_Directory/workflow.spec.yaml
* Updated plugins in workflow to 3.0.10
* Bumped Version
* Updated Changelog
```
```
=> Fix AD Backslash issue by updating plugin

workflows/Enrich_InsightIDR_Alerts_With_Threat_Intelligence_From_VirusTotal/Enrich_InsightIDR_Alerts_With_Threat_Intelligence_From_VirusTotal.icon, workflows/Enrich_InsightIDR_Alerts_With_Threat_Intelligence_From_VirusTotal/help.md, workflows/Enrich_InsightIDR_Alerts_With_Threat_Intelligence_From_VirusTotal/workflow.spec.yaml
=> Update Enrich_InsightIDR_Alerts_With_Threat_Intelligence_From_VirusTotal workflow with latest VT plugin

workflows/Look_Up_Domains_with_Recorded_Future/Look_Up_Domains_with_Recorded_Future.icon, workflows/Look_Up_Domains_with_Recorded_Future/help.md, workflows/Look_Up_Domains_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_Hashes_with_Recorded_Future/Look_Up_Hashes_with_Recorded_Future.icon, workflows/Look_Up_Hashes_with_Recorded_Future/help.md, workflows/Look_Up_Hashes_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_IPs_with_Recorded_Future/Look_Up_IPs_with_Recorded_Future.icon, workflows/Look_Up_IPs_with_Recorded_Future/help.md, workflows/Look_Up_IPs_with_Recorded_Future/workflow.spec.yaml, workflows/Look_Up_URLs_with_Recorded_Future/Look_Up_URLs_with_Recorded_Future.icon, workflows/Look_Up_URLs_with_Recorded_Future/help.md, workflows/Look_Up_URLs_with_Recorded_Future/workflow.spec.yaml
[urls.pdf](https://github.com/rapid7/insightconnect-workflows/files/5520493/urls.pdf)
[hash.pdf](https://github.com/rapid7/insightconnect-workflows/files/5520502/hash.pdf)
[domains.pdf](https://github.com/rapid7/insightconnect-workflows/files/5520503/domains.pdf)
[ip.pdf](https://github.com/rapid7/insightconnect-workflows/files/5520504/ip.pdf)
=> Update Recorded Future plugin in existed workflows

workflows/Enrich_Malicious_URL_Alerts_From_InsightIDR_With_Threat_Crowd/Enrich_Malicious_URL_Alerts_From_InsightIDR_With_Threat_Crowd.icon, workflows/Enrich_Malicious_URL_Alerts_From_InsightIDR_With_Threat_Crowd/help.md, workflows/Enrich_Malicious_URL_Alerts_From_InsightIDR_With_Threat_Crowd/workflow.spec.yaml
=> revised artifact name, version bump

workflows/Send_Remediated_Vulnerabilities_Message_in_Microsoft_Teams_from_InsightVM/help.md, workflows/Send_Remediated_Vulnerabilities_Message_in_Microsoft_Teams_from_InsightVM/workflow.spec.yaml
=> Clean up unicode double quotes in new workflow

workflows/Manage_Watched_Domains_with_Darktrace_from_Slack/Manage_Watched_Domains_with_Darktrace_from_Slack.icon, workflows/Manage_Watched_Domains_with_Darktrace_from_Slack/help.md, workflows/Manage_Watched_Domains_with_Darktrace_from_Slack/workflow.spec.yaml
```
darktrace-slack-workflow⚡ ⇒  icon-validate .
[*] Executing …
```
=> Update Darktrace Manage Watched Domains workflow for Slack

workflows/Manage_Watched_Domains_with_Darktrace_from_Microsoft_Teams/help.md, workflows/Manage_Watched_Domains_with_Darktrace_from_Slack/help.md
=> Darktrace Help

workflows/InsightVM_Top_25_Remediations_to_JIRA/InsightVM_Top_25_Remediations_to_JIRA.icon, workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md, workflows/InsightVM_Top_25_Remediations_to_JIRA/workflow.spec.yaml
=> update workflow actions for Create Solution-Based Tickets with Jira from InsightVM

workflows/Alert_on_New_Unknown_Assets_Discovered_by_InsightVM_with_Slack/help.md, workflows/Alert_on_New_Unknown_Assets_Discovered_by_InsightVM_with_Slack/workflow.spec.yaml
=> Remove unicode double quotes from spec

workflows/Delete_O365_Emails_With_Slack/Delete_O365_Emails_With_Slack.icon, workflows/Delete_O365_Emails_With_Slack/help.md, workflows/Delete_O365_Emails_With_Slack/workflow.spec.yaml
Workflow Find and Delete Emails in Office 365 from Slack Bug
<details>
```
[*] Executing validator WorkflowScreenshotValidator
[*] …
```
=> Workflow Find and Delete Emails in Office 365 from Slack Bug

workflows/Top_Remediations_For_Asset_In_Teams/workflow.spec.yaml
=> MC-164 & MC-165 Correction - Removed extra white space

workflows/Send_Remediated_Vulnerabilities_Message_in_Microsoft_Teams_from_InsightVM/Send_Remediated_Vulnerabilities_Message_in_Microsoft_Teams_from_InsightVM.icon, workflows/Send_Remediated_Vulnerabilities_Message_in_Microsoft_Teams_from_InsightVM/help.md, workflows/Send_Remediated_Vulnerabilities_Message_in_Microsoft_Teams_from_InsightVM/workflow.spec.yaml
added logic to reduce noise for trivial vulnerability remediations
Tested in integrations lab with dev Teams account
=> Updated workflow to check vuln risk

.github/workflows/workflow_validator.yml
* Added a Github Action to validate workflows at the time of PR
=> Add workflow validator GH action

workflows/InsightVM_Top_25_Remediations_to_JIRA/InsightVM_Top_25_Remediations_to_JIRA.icon, workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md
=> SOAR-2883 Update help and add filter to only allow assets scanned in last 30 days

workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/Quarantine_Endpoint_with_SentinelOne_from_Slack.icon, workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/help.md, workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack/workflow.spec.yaml
- Update .icon file to publish to extension library (specifically update pattern match because it was failing on the unquarantine command)
```
ekim@BOS-MBP-8175:~/go/src/github.com/rapid7/insightconnect-workflows/workflows/Quarantine_Endpoint_with_SentinelOne_from_Slack|SOAR4199_Update_Workflow⚡ ⇒  icon-validate .
[*] Executing …
```
=> SOAR4199_Update_SentinelOne_Quarantine_Asset_Workflow

workflows/Enrich_Indicators_with_OSINT_from_Microsoft_Teams/Enrich_Indicators_with_OSINT_from_Microsoft_Teams.icon, workflows/Enrich_Indicators_with_OSINT_from_Microsoft_Teams/help.md, workflows/Enrich_Indicators_with_OSINT_from_Microsoft_Teams/workflow.spec.yaml
I did not change any of the workflow steps. I included two parameters and use them in trigger.
=> SOAR-4446 - Update Enrich Indicators with OSINT from Microsoft Teams to use parameters

workflows/Enrich_Indicators_with_OSINT_from_Microsoft_Teams/help.md, workflows/Enrich_Indicators_with_OSINT_from_Microsoft_Teams/workflow.spec.yaml
Just bumping the major version.
=> [no ticket] - Bump major version for Enrich Indicators using OSINT in MS Teams

workflows/Open_Tickets_In_ServiceNow_For_Newly_Discovered_Vulns/workflow.spec.yaml
=> obsolete the current open tickets wf

workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/help.md, workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/workflow.spec.yaml
patch version bump, fixed cloud_enabled tag
=> fixed cloud_enabled tag

workflows/Top_Remediations_For_Asset_In_Teams/Top_Remediations_For_Asset_In_Teams.icon, workflows/Top_Remediations_For_Asset_In_Teams/help.md, workflows/Top_Remediations_For_Asset_In_Teams/workflow.spec.yaml
This removes a give in the error message on Top Remediations for Asset in Teams
Imported the WF into ICON to verify file integrity. 
```
RMT-MBP-5357:Top_Remediations_For_Asset_In_Teams jmcadams$ icon-validate .
[*] Executing …
```
=> [No Ticket] - Fix gif in error message

workflows/Open_Tickets_in_ServiceNow_for_Newly_Discovered_Vulns/help.md, workflows/Open_Tickets_in_ServiceNow_for_Newly_Discovered_Vulns/workflow.spec.yaml
This PR bumps the workflow Open Tickets in ServiceNow for Newly Discovered Vulns version 1.0.0 -> 1.0.1 and removes the obsolute status tag. This will allow this workflow to release to the Exension Library.
```
```
=> SOAR-5122: Version bump and remove obsolute status

workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd.icon, workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/help.md, workflows/Enrich_Hash_With_Threat_Intelligence_From_Threat_Crowd/workflow.spec.yaml, workflows/Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT/Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT.icon, workflows/Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT/help.md, workflows/Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT/workflow.spec.yaml, workflows/Enrich_Process_Hash_with_OSINT_from_Slack/Enrich_Process_Hash_with_OSINT_from_Slack.icon, workflows/Enrich_Process_Hash_with_OSINT_from_Slack/help.md, workflows/Enrich_Process_Hash_with_OSINT_from_Slack/workflow.spec.yaml
Enrich Hash with Threat Intelligence from Threat Crowd
<details>
```
[*] Executing validator WorkflowScreenshotValidator
[*] Executing …
```
=> Update Threat Crowd associated workflows

workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams.icon, workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/help.md, workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/Block_Host_with_Palo_Alto_Firewall_from_Slack.icon, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/help.md, workflows/Block_Host_with_Palo_Alto_Firewall_from_Slack/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams.icon, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/help.md, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Microsoft_Teams/workflow.spec.yaml, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack.icon, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/help.md, workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/workflow.spec.yaml
All workflows tested and updated to use Workflow Parameters.
<details>
```
[*] Validating workflow at .\Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams\
[*] …
```
=> MC-349 - Fix Palo Alto Blocking Workflows

workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert.icon, workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/example_idr_alert/alert.json.example, workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/help.md
This PR fixes several issue with the Enrich Indicators with RF WF. 
* Updates the RF plugin to the latest version
* Fixes outputs to match new plugin version output
* Continue on failure added to RF actions to account for 404 errors
Tested locally and verified working. Negative tested locally and verified continue on failure works as well.
=> Fix Enrich Indicators with Recorded Future WF

workflows/Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT/workflow.spec.yaml, workflows/Enrich_Malicious_IP_Address_Alerts_from_InsightIDR_with_OSINT/workflow.spec.yaml, workflows/Forward_Alerts_from_InsightIDR_to_Slack/workflow.spec.yaml
Update Product tag on IDR Workflows No workflow updates.
```
```
=> Update Product tag on IDR Workflows

workflows/Orchestrate_Automox_Vulnerability_Sync_with_Rapid7_InsightVM/workflow.spec.yaml
Identified a type of `pn` instead of `png` for extension of one of the screenshots for the Automox Vulnerability Sync with Rapid7 InsightVM workflow. There are no changes to the workflow itself.
```
```
=> Fix type in workflow.spec.yaml screenshot section for Orchestrate Automox Vulnerability Sync with Rapid7 InsightVM workflow

.github/workflows/workflow_validator.yml
-Bump Github actions to Python 3.8
```
```
=> [SOAR-8647] Bump Github actions to Python 3.8

workflows/Orchestrate_Automox_Vulnerability_Sync_with_Rapid7_InsightVM/Orchestrate_Automox_Vulnerability_Sync_with_Rapid7_InsightVM.icon, workflows/Orchestrate_Automox_Vulnerability_Sync_with_Rapid7_InsightVM/help.md, workflows/Orchestrate_Automox_Vulnerability_Sync_with_Rapid7_InsightVM/workflow.spec.yaml
The changes of this PR include:
1. Updating the workflow report generation step with an improved SQL query to match on hostnames and FQDNs
2. Upgrade workflow to use the latest Automox plugin (awaiting release here https://github.com/rapid7/insightconnect-plugins/pull/1226)
```
```
=> Automox/InsightVM Workflow: Updated SQL query in report generation 
